implemented Backend plugin for create OpenFGA authz model
web-seven/backstage-plugins pull request #69
Opened 2024-10-15 13:54 UTC by Catalin4513

2024-10-15 14:57 UTC, ionition commented on plugins/backstage-plugin-openfga-backend/src/permitions/permissionsCollector.ts
> +function permitionsPaths(config: Config) {
the correct word is "permissions", please correct it in other places too

2024-10-15 15:02 UTC, ionition commented on plugins/backstage-plugin-openfga-backend/src/permitions/permissionsCollector.ts
> +        console.error(`Error fetching permissions from ${url}:`, error);
remove console.logs and add logger.error instead

2024-10-15 15:54 UTC, evghen1 requested changes

2024-10-15 15:54 UTC, evghen1 commented on app-config.yaml
> +    authorizationModelId: ${OPENFGA_AUTHORIZATION_MODEL_ID}
@Catalin4513 Please do not use model ID, because this plugin creates and update it, it shall be dynamic

2024-10-15 15:54 UTC, evghen1 commented on packages/backend/src/index.ts
> +backend.add(import('@web-seven/backstage-plugin-backstage-plugin-openfga-backend'));
@Catalin4513 Duplicate prefix

2024-10-15 15:54 UTC, evghen1 commented on plugins/backstage-plugin-openfga-backend/package.json
> +  "name": "@web-seven/backstage-plugin-backstage-plugin-openfga-backend",
@Catalin4513 Duplicate prefix

2024-10-15 15:54 UTC, evghen1 commented on plugins/backstage-plugin-openfga-backend/src/fga/openfgaClient.ts
> +        apiUrl: config.getOptionalString('openfga.auth.apiUrl') ?? '',
@Catalin4513 It can't be optional, client can't be created without configuration.

2024-10-15 15:54 UTC, evghen1 commented on plugins/backstage-plugin-openfga-backend/src/fga/openfgaClient.ts
@Catalin4513 Please combine all functions of client under class.

2024-10-15 15:54 UTC, evghen1 commented on plugins/backstage-plugin-openfga-backend/src/fga/openfgaClient.ts
@Catalin4513 Add comments to functions

2024-10-15 15:54 UTC, evghen1 commented on plugins/backstage-plugin-openfga-backend/src/permissions/permissionsCollector.ts
@Catalin4513 Use classes

2024-10-15 15:54 UTC, evghen1 commented on plugins/backstage-plugin-openfga-backend/src/service/router.ts
> +    logger.info('PONG!');
@Catalin4513 Remove it please that will grow unnecessary logs

2024-10-15 15:54 UTC, evghen1 commented on yarn.lock
@Catalin4513 this file has conflicts artifacts.

2024-10-15 15:54 UTC, evghen1 commented on app-config.yaml
> +  auth:
@Catalin4513 Please do not use auth key, simple use openfga.token and openfga.host

2024-10-15 15:54 UTC, evghen1 commented on plugins/backstage-plugin-openfga-backend/src/fga/openfgaClient.ts
@Catalin4513 rename file to src/service/openfgaClient.ts

2024-10-17 06:33 UTC, evghen1 requested changes

2024-10-17 06:33 UTC, evghen1 commented on app-config.yaml
> +  baseUrl: /:scope/guest-mock.json
@Catalin4513 remove this settings you no use it right, this is url to this plugin api for frontend, but for access openfga api please use `openfga.host`

2024-10-17 06:33 UTC, evghen1 commented on plugins/backstage-plugin-openfga-backend/src/permissions/permissionsCollector.ts
@Catalin4513 Please make it to be class based permission collector, when you name like this (and is good), shall be defined as consolidated object with features (methods) inside and all dependencies for all methods to comes into constructor.

2024-10-17 06:33 UTC, evghen1 commented on plugins/backstage-plugin-openfga-backend/src/plugin.ts
> +export const backstagePluginOpenfgaPlugin = createBackendPlugin({
@Catalin4513 Please rename it to simple openfgaPlugin, and keep in mind you will have conflicts soon with thid PR: https://github.com/web-seven/backstage-plugins/pull/70

2024-10-17 06:33 UTC, evghen1 commented on plugins/backstage-plugin-openfga-backend/src/service/openfgaClient.ts
> +    const apiUrl = config.getString('openfga.baseUrl');
@Catalin4513 As i said before, this is not openfga api url.

2024-10-17 08:33 UTC, evghen1 requested changes
@Catalin4513 Please take a look and resolve conflicts

2024-10-17 13:46 UTC, evghen1 requested changes

2024-10-17 13:46 UTC, evghen1 commented on plugins/backstage-plugin-openfga-backend/src/service/openfgaClient.ts
@Catalin4513 rename file to OpenFgaClient.ts

2024-10-17 13:46 UTC, evghen1 commented on plugins/backstage-plugin-openfga-backend/src/permissions/permissionsCollector.ts
@Catalin4513 rename file to PermissionCollector.ts

2024-10-17 14:46 UTC, evghen1 approved these changes

2024-10-17 14:46 UTC, merged